server:
  port: 8081
  servlet:
    session:
      timeout: 86400
spring:
  datasource:
    username: hap_dev
    password: hap_dev
    url: jdbc:mysql://192.168.21.128:3306/witty?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    #数据库索引
    database: 0
    # Redis服务器地址
    host: localhost
    port: 6379
    timeout: 1000
  application:
    name: witty-client
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.li.org.mapper

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#springcloud
eureka:
  client:
    register:
      with:
        eureka: false
    service-url:
      defaultZone: http://localhost:1001/eureka
