server:
  port: 8081

spring:
  datasource:
    username: hecdev
    password: hecdev
    url: jdbc:mysql://192.168.21.128:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.li.org
 